{% set version = "2.0.8" %}

package:
  name: gmpy2
  version: {{ version }}

source:
  fn: gmpy2-master.zip
  url: https://github.com/aleaxit/gmpy/archive/8091d45a604b29022d9299f77d1379211f9bb666.zip
  sha256: 61d0631b68576bde8e93d439f3cf06f97f4445f855633ccd20ae133b282869ff

build:
  number: 0
  skip: true        # [win and py<35]
  features:
    - vc14          # [win and py>=35]
  script:
    - python setup.py install --shared=$PREFIX                         # [unix]
    - python setup.py build_ext -f --shared=%LIBRARY_PREFIX% install   # [win]

requirements:
  build:
    - toolchain
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - python
  run:
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - python

test:
  imports:
    - gmpy2

about:
  home: https://pypi.python.org/pypi/gmpy2
  license: LGPL 3
  license_file: COPYING.LESSER
  summary: 'GMP/MPIR, MPFR, and MPC interface to Python 2.6+ and 3.x'

extra:
  recipe-maintainers:
    - isuruf
