{% set version = "2.1.0b1" %}

package:
  name: gmpy2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gmpy2/gmpy2-{{ version }}.tar.gz
  sha256: 30b30707c782e4e355c920d1d998751ffc1b2189070a88a482f08c6e35511939
  patches:
    - win_setup.diff

build:
  number: 0
  skip: true        # [win and py<35]
  script:
    - python setup.py install

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - python
    - pip
  run:
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - python

test:
  imports:
    - gmpy2

about:
  home: https://pypi.python.org/pypi/gmpy2
  license: LGPL 3
  license_file: COPYING.LESSER
  summary: 'GMP/MPIR, MPFR, and MPC interface to Python 2.6+ and 3.x'

extra:
  recipe-maintainers:
    - isuruf
