{% set version = "2.0.8" %}

package:
  name: gmpy2
  version: {{ version }}

source:
  fn: gmpy2-{{version}}.zip
  url: https://pypi.io/packages/source/g/gmpy2/gmpy2-{{ version }}.zip
  sha256: dd233e3288b90f21b0bb384bcc7a7e73557bb112ccf0032ad52aa614eb373d3f

build:
  number: 1
  skip: true        # [win and not py35]
  features:
    - vc14          # [win and py35]
  script:
    - python setup.py install --shared=$PREFIX                                          # [unix]
    - python setup.py build_ext -f --shared=%LIBRARY_PREFIX% -DMSC_USE_DLL=1 install    # [win]

requirements:
  build:
    - toolchain
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr 3.*
    - mpc
    - python
  run:
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr 3.*
    - mpc
    - python

test:
  requires:
    - python 2.7.*  # [py27]
    - python 3.4.*  # [py34]
    - python 3.5.*  # [py35]
  imports:
    - gmpy2

about:
  home: https://pypi.python.org/pypi/gmpy2
  license: LGPL 3
  license_file: COPYING.LESSER
  summary: 'GMP/MPIR, MPFR, and MPC interface to Python 2.6+ and 3.x'

extra:
  recipe-maintainers:
    - isuruf
